name: Clone Repository
on:
  push: # On every push on any branch
  jobs:
  Build: # Job name
  runs-on: ubuntu-latest # Operating system selection
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: "adopt" # See 'Supported distributions' for available options
        java-version: "21"
    - run: java HelloWorldApp.java
