  name: pps-ci-lab
  on:
    push:
  jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        - name: Install Java
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '15'
        - run: ./gradlew clean build
