name: pps-ci-lab

on:
  push:  # Runs on every push to any branch

jobs:
  Build:  # Job name
    runs-on: ubuntu-latest  # Correct indentation (2+ spaces under "Build")
    env:
      TERM: dumb  # Simplifies log output

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated from v2 to v4

      - name: Set up JDK 15
        uses: actions/setup-java@v3  # Official Java setup action
        with:
          java-version: '15'  # Must be a string (quotes required)
          distribution: 'temurin'  # Recommended JDK distribution

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew  # Ensures Gradle Wrapper is executable

      - name: Build and Test
        run: ./gradlew check  # Runs checks (tests + validation)