name: Test Build
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # custom name Checkout the repository
        uses: actions/checkout@v6 # Action implemented in this repository, tag starting with "v6"
      - uses: actions/setup-java@v5 # Action implemented in repository "actions/setup-java" tag starting with "v5"
        with: # Actions parameters (action name omitted)
          java-version: 21
          distribution: ''
      - name: Build
        run: ./gradlew build